Default: &defaults
  host: "*4"
  port: 3000

Development:
  <<: *defaults
  approot: ""

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://www.yesodweb.com"
  <<: *defaults
